version: 2.1

workflows:
  version: 2
  commit-test-build-deploy:
    jobs:
      - tests
      - build:
          requires:
            - tests
          filters:
            branches:
              ignore: /.*/  # Skip the build job if tests fail
      - deploy:
          requires:
            - build

jobs:
  tests:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      # Add your test steps here
      - run:
          name: Install dependencies and run tests
          command: |
            echo "Installing dependencies..."
            pip install -r requirements.txt
            python manage.py test lorenzo_barone || circleci step halt

  build:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      # Add your build steps here
      - run:
          name: Build and test
          command: |
            echo "Building and testing..."
            # Insert your build and test commands here

  deploy:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      # Add your deployment steps here
      - run:
          name: Deploy to production
          command: |
            echo "Deploying to production..."
            # Insert your deployment commands here
