version: 2.1

workflows:
  version: 2
  commit-test-build-deploy:
    jobs:
      - tests
      - build:
          requires:
            - tests
          filters:
            branches:
              ignore: /.*/  # Skip the build job if tests fail
          when: <<pipeline.parameters.test_passed>>

jobs:
  tests:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      # Add your test steps here
      - run:
          name: Install dependencies and run tests
          command: |
            echo "Installing dependencies..."
            pip install -r requirements.txt
            python manage.py test lorenzo_barone | tee test-results.txt
            test_result=$?
            if [ $test_result -ne 0 ]; then
              echo "Tests failed. Halting pipeline..."
              circleci step halt
            else
              echo "Tests passed. Proceeding with the pipeline..."
              echo "test_passed=true" >> $BASH_ENV
            fi

  build:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      # Add your build steps here
      - run:
          name: Build and test
          command: |
            echo "Building and testing..."
            # Insert your build and test commands here

parameters:
  test_passed:
    type: boolean
    default: false

