version: 2.1

workflows:
  version: 2
  commit-test-build-deploy:
    jobs:
      - commit
      - tests:
          requires:
            - commit
          post-steps:
            - store_test_results:
                path: test-results.xml
      - build:
          requires:
            - tests
      - deploy:
          requires:
            - build

jobs:
  commit:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      # Add your commit steps here
      - run:
          name: Commit changes
          command: |
            echo "Committing changes..."
            # Insert your commit commands here

  tests:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      # Add your test steps here
      - run:
          name: Install dependencies and run tests
          command: |
            echo "Installing dependencies..."
            pip install --upgrade pip
            pip install -r requirements.txt
            python -m xmlrunner discover --output-file test-results.xml

  build:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      # Add your build steps here
      - run:
          name: Build and test
          command: |
            echo "Building and testing..."
            # Insert your build and test commands here

  deploy:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      # Add your deployment steps here
      - run:
          name: Deploy to production
          command: |
            echo "Deploying to production..."
            # Insert your deployment commands here
