# Generated by Django 4.0.5 on 2022-06-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorenzo_barone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Lorenzo Barone', max_length=255),
        ),
    ]
