# Generated by Django 4.0.5 on 2022-07-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorenzo_barone', '0011_alter_post_category_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='')),
            ],
        ),
    ]
