# Generated by Django 4.0.5 on 2022-07-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lorenzo_barone', '0012_multipleimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleImage',
        ),
    ]
